### ISSUE TITLE
Project Milestone #1

### ISSUE THREAD

**Issue by caeles87** [edsyoo/lunch_vote#5]
# Initial Project Foundation
### README:
- [ ] Describe, in detail, the overarching project idea
- [ ] Detail minimum system requirements
- [ ] Detail the setup steps required for a fresh installation

# Core Features for a minimum viable product:
- [ ] Allow users to create a scheduled lunch event.
- [ ] Allow original event creator to invite attendees.
- [ ] Allow for users to register new lunch locations in personalized selection pools.
